import {useParams,Link} from "react-router-dom"; import {areas} from "../../components/PracticeAreas/PracticeAreas"; import PageHero from "../../components/PageHero/PageHero"; import "./Page.css";
const details={
 civil:["Civil Law",["Property disputes","Recovery matters","Injunction matters","Declaration suits","Specific performance matters","Partition and separate possession","Possession-related disputes","Contractual disputes","Civil documentation","Legal notices","Civil litigation support"]],
 criminal:["Criminal Law",["Criminal complaints","Bail matters","Anticipatory bail matters","Regular bail matters","Criminal proceedings","Complaints and representations","Criminal defence assistance","Legal notices and responses","Criminal litigation support"]],
 family:["Family Law",["Divorce-related matters","Maintenance proceedings","Custody and guardianship","Domestic disputes","Partition among family members","Succession-related matters","Inheritance matters","Family settlements","Legal notices relating to family disputes"]],
 "high-court":["High Court Matters",["Legal consultation","Drafting and preparation of legal documents","Writ-related matters","Civil proceedings","Criminal proceedings","Appeals and revisions","Legal research","Litigation support"]],
 property:["Property & Real Estate Law",["Property title verification","Sale deed scrutiny","Parent document examination","Encumbrance verification","Khata document scrutiny","Mutation document examination","RTC and revenue record examination","Property tax document verification","Conversion documents","Layout approval documents","Development-related documents","Joint development agreements","Sale and purchase documentation","Property dispute matters","Partition matters","Possession-related matters","Legal notices concerning property"]],
 "title-verification":["Property Title Verification",["Current Sale Deed","Previous Sale Deeds","Mother/Parent Documents","Gift Deed","Partition Deed","Release Deed","Settlement Deed","Will","Probate/Letters of Administration, where applicable","Khata Certificate","Khata Extract","Mutation Records","RTC","Encumbrance Certificate","Conversion Order","Approved Layout Plan","Sanctioned Plan","Building Plan","Property Tax Receipts","Possession Certificate","Allotment Letter","Development Agreement","Joint Development Agreement","Power of Attorney","Other supporting documents"]],
 "legal-scrutiny":["Legal Scrutiny & Due Diligence",["Collection of relevant documents","Examination of title documents","Verification of continuity of title","Examination of ownership documents","Review of encumbrance records","Examination of revenue and municipal records","Identification of gaps or inconsistencies","Review of supporting documents","Legal research wherever required","Preparation of legal observations/opinion"]],
 "legal-drafting":["Sale Deed and Property Document Drafting",["Sale Deeds","Agreements to Sell","Gift Deeds","Partition Deeds","Release Deeds","Settlement Deeds","Rectification Deeds","Confirmation Deeds","Memorandum of Understanding","Joint Development Agreements","General/Special Power of Attorney","Lease Agreements","Rent Agreements","Construction Agreements","Partnership-related documents","Affidavits","Undertakings","Declarations","Legal Notices","Replies to Legal Notices","Applications and representations"]],
 "civil-litigation":["Civil Litigation",["Civil proceedings","Civil disputes","Pleadings","Legal notices","Property-related litigation","Contractual disputes","Litigation support"]],
 "legal-notices":["Legal Notices",["Property disputes","Recovery of money","Breach of contract","Non-payment of dues","Tenancy and rental disputes","Possession disputes","Sale agreement disputes","Specific performance","Family disputes","Consumer-related grievances","Deficiency in services","Other civil and commercial disputes"]],
 "agreements-contracts":["Agreements & Contracts",["Agreement drafting and review","Contract review","Sale and purchase agreements","Lease agreements","Rent agreements","Construction agreements","Partnership-related documents","Memoranda of Understanding"]],
 "corporate-commercial":["Corporate & Commercial Legal Matters",["Agreement drafting and review","Contract review","Legal notices","Vendor agreements","Service agreements","Employment-related documentation","Non-Disclosure Agreements","Memoranda of Understanding","Partnership documentation","Commercial dispute assistance","Legal due diligence","Contractual risk identification"]],
};
export default function PracticeAreaDetails(){const {slug}=useParams(); const d=details[slug]||[areas.find(a=>a[2]===slug)?.[1]||"Legal Service",[]]; return <><PageHero eyebrow="NEEM LEGAL · AREAS OF PRACTICE" title={<>{d[0]}<br/><span>Professional Legal Assistance</span></>} copy="The scope of assistance depends upon the facts of each matter, the documents supplied and applicable law."/><section className="section"><div className="container"><div className="practice-detail-content"><span className="eyebrow">SERVICES MAY INCLUDE</span><h2 className="display section-title">{d[0]}<br/><span>Services and support.</span></h2><div className="practice-services-list">{d[1].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></div>)}</div><p className="section-copy">Documents are reviewed and services are provided based on the facts, instructions and legal requirements applicable to the particular matter.</p><Link to="/consultation" className="signature-button">Book a Consultation ↗</Link></div></div></section></>}
