import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import "./Introduction.css";
const values=[
 {number:"01",title:"Careful Examination",text:"Facts and documents are examined with attention to detail."},
 {number:"02",title:"Clear Legal Analysis",text:"Legal issues and available options are explained clearly."},
 {number:"03",title:"Practical Solutions",text:"The focus is on legally appropriate and practical courses of action."},
];
export default function Introduction(){return <section className="intro"><div className="container intro-container"><motion.div className="intro-top" initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><div className="intro-label"><span className="intro-label-line"/><span>The NEEM LEGAL Approach</span></div><span className="intro-location">Bengaluru · Karnataka</span></motion.div><div className="intro-main"><motion.div className="intro-heading" initial={{opacity:0,x:-30}} whileInView={{opacity:1,x:0}} viewport={{once:true}}><p className="intro-overline">Professional legal assistance</p><h2>Understand<br/>before you <em>act.</em></h2><div className="intro-heading-line"/></motion.div><motion.div className="intro-copy" initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><p className="intro-description">NEEM LEGAL is a legal practice focused on professional legal assistance, legal documentation, property-related legal scrutiny, litigation support and advisory services. The objective is to help clients understand their legal position and take informed decisions based on the facts and applicable law.</p><div className="intro-values">{values.map(v=><div className="intro-value" key={v.number}><span className="intro-value-number">{v.number}</span><div className="intro-value-content"><strong>{v.title}</strong><p>{v.text}</p></div><span className="intro-value-arrow">↗</span></div>)}</div><Link to="/about" className="intro-link"><span>About NEEM LEGAL</span><b>↗</b></Link></motion.div></div><motion.div className="intro-visual" initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><div className="intro-image-wrap"><img src="https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&w=1600&q=90" alt="Law library"/><div className="intro-image-overlay"/><div className="intro-image-top"><span>NEEM LEGAL</span><span>02 / 06</span></div><div className="intro-image-caption"><span>OUR PHILOSOPHY</span><h3>Facts.<br/>Documents.<br/><em>Applicable law.</em></h3></div></div></motion.div></div></section>}
